bold = true
color_mode = "ansi" # ansi, rgb, none
palette = "matrix" # default, darker, pastel, matrix
rainbow = 25 # 0-255
turn_chance = 0.02 # 0.0-1.0
kinds = ["heavy"] # heavy, light, curved, knobby, emoji, outline, dots, blocks, sus
num_pipes = 2
delay_ms = 50
reset_threshold = 0.09 # 0.0-1.0
