# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Colors Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$cachylgreen = rgba(82dcccff)
$cachymgreen = rgba(00aa84ff)
$cachydgreen = rgba(007d6fff)
$cachylblue = rgba(626880FF)
$cachymblue = rgba(949CBBFF)
$cachydblue = rgba(111826ff)
$cachywhite = rgba(ffffffff)
$cachygrey = rgba(ddddddff)
$cachygray = rgba(798bb2ff)

# MONO
$black= rgb(2d2a2e)
$one= rgb(3f3a3f)
$two= rgb(514a50)
$three= rgb(625a60)
$four= rgb(746b6f)
$five= rgb(857b7e)
$six= rgb(978c8c)
$seven= rgb(a89e9c)
$eight= rgb(b9b1ad)
$nine= rgb(cbc5be)
$ten= rgb(dcd9cf)
$eleven= rgb(eeede0)
$white= rgb(fdfff1)

# COLORS
$red= rgb(fc5c65)
$orange= rgb(f19066)
$yellow= rgb(f7d794)
$green= rgb(c3e69f)
$teal= rgb(87dcc6)
$blue= rgb(7ed6df)
$purple= rgb(786fa6)
$pink= rgb(f78fb3)

# TINT
$light-red= rgb(fdaeab)
$light-orange= rgb(f7c7ab)
$light-yellow= rgb(faebc3)
$light-green= rgb(e0f3c8)
$light-teal= rgb(c2eddb)
$light-purple= rgb(bab7cb)
$light-pink= rgb(fac7d2)

# SHADE
$dark-red= rgb(94434a)
$dark-orange= rgb(8f5d4a)
$dark-yellow= rgb(928161)
$dark-green= rgb(788867)
$dark-teal= rgb(5a837a)
$dark-blue= rgb(558087)
$dark-purple= rgb(524d6a)
$dark-pink= rgb(925d71)
