# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager = $terminal -e yazi
$applauncher = wofi
$terminal = ghostty
$editor = $terminal -e nvim
$browser = vivaldi-stable
$player = strawberry
$resourceMonitor = $terminal -e btop
$idlehandler = swayidle -w timeout 120 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$priMon = DP-1
$secMon = HDMI-A-1
