source = ~/.config/hypr/config/defaults.conf

preload= /home/gronk-droid/gh/resources/wallpapers/21x9/eg_circle_tile.png
wallpaper= DP-3, /home/gronk-droid/gh/resources/wallpapers/21x9/eg_circle_tile.png

preload = /home/gronk-droid/gh/resources/wallpapers/16x9/flower_tree.png
wallpaper = DP-2, /home/gronk-droid/gh/resources/wallpapers/16x9/flower_tree.png