source = ~/.config/hypr/config/defaults.conf

preload= /home/gronk-droid/gh/resources/wallpapers/21x9/fern_tree.png
wallpaper= DP-2, /home/gronk-droid/gh/resources/wallpapers/21x9/fern_tree.png

preload = /home/gronk-droid/gh/resources/wallpapers/16x9/fern_tree.png
wallpaper = DP-1, /home/gronk-droid/gh/resources/wallpapers/16x9/fern_tree.png