source = ~/.config/hypr/config/defaults.conf

preload= /home/gronk-droid/gh/resources/wallpapers/21x9/cesenatico_house_left.png
wallpaper= DP-2, /home/gronk-droid/gh/resources/wallpapers/21x9/cesenatico_house_left.png

preload = /home/gronk-droid/gh/resources/wallpapers/16x9/cesenatico_house_right.png
wallpaper = DP-1, /home/gronk-droid/gh/resources/wallpapers/16x9/cesenatico_house_right.png