# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/0.45.0/Configuring/Monitors/

monitor = DP-1, 2560x1440@239.97Hz, 0x0, 1.0
monitor = HDMI-A-1, 3440x1440@99.98Hz, 0x-1440, 1.0
# monitor = HDMI-A-1, 3440x1440@99.98Hz, -3440x0, 1.0
# monitor = DP-2, 2560x1440@239.97Hz, auto-right, 1.0
# monitor = DP-2, 2560x1440@239.97Hz, 3440x-640, 1.0, transform, 3


# A791B3
# 836993

#    ╻ ╻┏━┓┏━┓╻┏ ┏━┓┏━┓┏━┓┏━╸┏━╸┏━┓
#    ┃╻┃┃ ┃┣┳┛┣┻┓┗━┓┣━┛┣━┫┃  ┣╸ ┗━┓
#    ┗┻┛┗━┛╹┗╸╹ ╹┗━┛╹  ╹ ╹┗━╸┗━╸┗━┛


workspace = 1, m[DP-1], default:true
workspace = 2, m[DP-1], default:true
workspace = 3, m[DP-1], default:true
workspace = 4, m[DP-1], default:true
workspace = 5, m[DP-1], default:true

workspace = 6, m[HDMI-A-1], default:true
workspace = 7, m[HDMI-A-1], default:true
workspace = 8, m[HDMI-A-1], default:true
workspace = 9, m[HDMI-A-1], default:true
workspace = 10, m[HDMI-A-1], default:true

# If you need to scale ,things like steam etc, please uncomment these lines.
# Adjust GDK_SCALE accordingly to your liking.
xwayland {
 force_zero_scaling = true       # Unscale XWayland
}

# env = GDK_SCALE, 1.25                   # GDK Scaling Factor
